# Generated by Django 5.2.1 on 2025-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='pic_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
