# Generated by Django 5.2.1 on 2025-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0002_alter_user_info_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
