# Generated by Django 5.2.1 on 2025-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineBot', '0003_user_info_response'),
    ]

    operations = [
        # Ensure User_Info table exists with all required fields
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "LineBot_user_info" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "uid" varchar(50) NOT NULL,
                "name" varchar(255) NOT NULL,
                "mtext" varchar(255) NOT NULL,
                "mdt" datetime NOT NULL,
                "pic_url" varchar(255) NULL,
                "response" varchar(255) NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS LineBot_user_info;"
        ),
    ]
