"""
Django settings for ChatBot project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!




# OpenAI API Key - Replace with your actual key
OPENAI_API_KEY = os.getenv('API_KEY') # TODO: Replace with actual key

# Model Settings
COMPLEX_LLM_MODEL = os.getenv('COMPLEX_LLM_MODEL', 'gpt-4.1-nano-2025-04-14')  # Primary model for complex tasks
LIGHTWEIGHT_LLM_MODEL = os.getenv('LIGHTWEIGHT_LLM_MODEL', 'gpt-4.1-nano-2025-04-14')  # Model for lightweight tasks
FALLBACK_MODEL = os.getenv('FALLBACK_MODEL', 'gpt-4.1-nano-2025-04-14')  # Will be set to fine-tuned model ID after training

# Fine-tuning Settings
FINE_TUNING_EPOCHS = 3
FINE_TUNING_BATCH_SIZE = 4

# Django
SECRET_KEY='y_e2*mxk@ygc@p!z!z-5)#tb209nr2#)^w0evj*--ov(lq77pa'

# Agent Settings
MAX_ITERATIONS = 10
AGENT_TEMPERATURE = 0
MEMORY_THRESHOLD = 10

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LineBot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ChatBot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ChatBot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration for Agent Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} | {name} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'agent_formatter': {
            'format': '\n🤖 AGENT LOG [{levelname}] {asctime}\n' + 
                     '📍 {name}\n' +
                     '💭 {message}\n' + 
                     '=' * 80,
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'tool_formatter': {
            'format': '\n🔧 TOOL EXECUTION [{levelname}] {asctime}\n' + 
                     '📍 {name}\n' +
                     '⚙️  {message}\n' + 
                     '-' * 60,
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'agent_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'agent_formatter',
            'level': 'INFO',
        },
        'tool_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'tool_formatter',
            'level': 'INFO',
        },
    },
    'loggers': {
        'LineBot.agent.react_agent': {
            'handlers': ['agent_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'LineBot.agent.tool_manager': {
            'handlers': ['tool_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'LineBot.agent.output_parser': {
            'handlers': ['agent_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'LineBot.agent.memory_manager': {
            'handlers': ['agent_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'LineBot': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# Agent Debug Settings
AGENT_DEBUG_MODE = True  # Set to False in production
SHOW_AGENT_THOUGHTS = True
SHOW_TOOL_EXECUTIONS = True
SHOW_OBSERVATIONS = True

